name: Bug Report
description: Report a bug in Antenna
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open app
        2. Click...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: macos-version
    attributes:
      label: macOS version
      placeholder: "e.g., 15.2"
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Antenna version
      placeholder: "e.g., 0.1.0"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console output (if relevant)
      render: shell
