name: Feature Request
description: Suggest a feature for Antenna
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
      placeholder: What problem does this solve for you?
